services:
  postgres:
    image: postgres:16
    container_name: engnet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresql_storage:/var/lib/postgresql/data
      - ./postgresql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - engnet_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
    container_name: engnet_server
    environment:
      - NODE_ENV=development
      - PORT=${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - "${SERVER_PORT}"
    volumes:
      - ./server:/usr/src/app
      - ./server/dist:/usr/src/app/dist
      - ./server/package.json:/usr/src/app/package.json
      - /usr/src/app/node_modules
    networks:
      - engnet_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: engnet_client
    environment:
      - NODE_ENV=development
      - PORT=${CLIENT_PORT}
    expose:
      - "${CLIENT_PORT}"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - engnet_network

  nginx:
    image: nginx:alpine
    container_name: engnet_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - server
      - client
    networks:
      - engnet_network

networks:
  engnet_network:
    driver: bridge
